name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:



jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - uses: actions/checkout@v4.1.6
      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Get CodeArtifact Auth Token and Set as Env Var
        run: |
          echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain harenako-api --domain-owner 779673422809 --region ${{ vars.AWS_REGION }} --query authorizationToken --output text)" >> $GITHUB_ENV
      - run: chmod +x gradlew
      - run: ./gradlew test

      

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: chmod +x format.sh
      - run: ./format.sh && git diff --exit-code